travis-ci/travis-core

lib/travis/services/remove_log.rb, spec/travis/services/remove_log_spec.rb
To not display an archived log, we have to create a log part (at least @joshk claims that should work).
=> remove archived log

lib/travis/api/v1/webhook/build/finished.rb, lib/travis/api/v1/webhook/build/finished/job.rb, lib/travis/testing/stubs.rb, spec/travis/api/v1/webhook/build/finished_spec.rb
This addresses this issue:
https://github.com/travis-ci/travis-ci/issues/2751
all tests are passing.
@svenfuchs please review :-)
=> include additional attributes to webhook payload

lib/travis/model/build/result_message.rb, lib/travis/model/job.rb
There are no tests for these two cases.
=> The state :received is a running state

db/migrate/20150210170900_index_requests_on_created_at.rb, db/structure.sql
Required for API build request throttling
=> Migration: add an index on requests created_at

lib/travis/services/find_build.rb, lib/travis/services/find_job.rb, spec/travis/services/find_build_spec.rb, spec/travis/services/find_job_spec.rb
rather than service `#new` options so that it plays nicely with the `#service` helper plumbing.
=> Accept exclude_config in params

db/migrate/20150317004600_add_slug_index_to_repositories.rb, db/structure.sql
/cc @joshk 
`EXPLAIN ANALYZE` on staging, before adding index:
```
=> EXPLAIN ANALYZE SELECT * FROM repositories WHERE ((owner_name || '/' || name)) ILIKE '%travis-ci/travis-co%';                                                                                                                                
QUERY PLAN                                                 
------------------------------------------------------------------------------------------------------------
Seq Scan on repositories  (cost=0.00..655.74 rows=2 width=234) (actual time=13.421..34.583 rows=3 loops=1)
Filter: ((((owner_name)::text || '/'::text) || (name)::text) ~~* '%travis-ci/travis-co%'::text)
Rows Removed by Filter: 15495
Total runtime: 34.630 ms
(4 rows)
```
`EXPLAIN ANALYZE` on staging, after adding index: …
=> Add index to repositories.slug

lib/travis/model/job/queue.rb, spec/travis/model/job/queue_spec.rb
(and sudo isn't needed) (and the feature flag is enabled)
=> Use the new container infrastructure if the repo is new

lib/travis/model/job/queue.rb, spec/travis/model/job/queue_spec.rb
Mainly this pushes most of the implementation to the instance level, and also implements a more "pattern match"-like way of doing things.
=> refactor the Job::Queue implementation

lib/travis/model/organization.rb, spec/travis/model/organization_spec.rb
@rkh can you review this please.
=> [do not merge] Allow Orgs to be marked as Educational

db/migrate/20150629231300_repos_add_invalidated_at.rb, db/structure.sql, lib/travis/config/defaults.rb, lib/travis/model/repository.rb, lib/travis/model/ssl_key.rb, lib/travis/services/find_repos.rb, spec/spec_helper.rb, spec/travis/addons/pusher/instruments/event_handler_spec.rb, spec/travis/model/repository_spec.rb
* ignores repos which are not accessible on GitHub on various repository scopes
* reduces key size during tests to reduce test run time
* comments broken pusher event handler spec (https://github.com/travis-ci/travis-core/commit/f56848ffb2fea94ff79a3cd9892ea2e4fa7de384#commitcomment-12006268, @drogus, could you have a look at this?)
=> Invalidated repos

lib/travis/api/v0/worker/job/test.rb, lib/travis/model/request.rb, lib/travis/model/request/pull_request.rb, lib/travis/testing/stubs.rb, spec/fixtures/github/api.github.com/repos/travis-repos/test-project-1/contents/.travis.yml_per_page_100_ref_ef34a166e2dd7780d40800890474f836c8b3fc34.json, spec/support/payloads.rb, spec/travis/api/v0/worker/job/test_spec.rb, spec/travis/model/request_spec.rb, spec/travis/requests/services/receive_spec.rb
This adds details about the PR to the worker payload.
See https://github.com/travis-pro/team-teal/issues/343
=> More detailed PR info

lib/travis/travis_yml_stats.rb, spec/travis/travis_yml_stats_spec.rb
Resolves https://github.com/travis-pro/team-sapphire/issues/93
=> Send notification data to Keen

lib/travis/model/branch.rb, lib/travis/model/build.rb, lib/travis/model/build/states.rb, lib/travis/model/build/update_branch.rb, spec/travis/model/build/states_spec.rb, spec/travis/model/build/update_branch_spec.rb, spec/travis/model/build_spec.rb
Should fix https://github.com/travis-pro/team-teal/issues/520. This is currently running on gatekeeper org production. Looks good to me.
=> Update branch on build create

lib/travis/model/build/config.rb
ref https://github.com/travis-ci/travis-build/pull/526
=> Add crystal to expansion keys

.rspec, lib/travis/model/request.rb, lib/travis/model/request/approval.rb, lib/travis/testing/stubs.rb, spec/travis/model/request/approval_spec.rb, spec/travis/model/request_spec.rb
Should fix https://github.com/travis-pro/team-teal/issues/538
=> Allow api requests no matter if pushes/pull_requests are enabled in settings

lib/travis/model/build/config/dist.rb, lib/travis/model/build/config/group.rb, spec/travis/model/build/config/dist_spec.rb, spec/travis/model/build/config/group_spec.rb
=> Check for :group || 'group' instead of :group || 'dist'

db/migrate/20151127153500_users_add_index_github_oauth_token.rb, db/migrate/20151127154200_annotations_add_index_job_id.rb, db/migrate/20151127154600_broadcasts_add_index_recipient_id_and_recipient_type.rb
These have bee run on staging of .com and .org without problems
=> Indexing to reduce sequential scans

db/migrate/20151202122200_users_add_first_logged_in_at.rb
=> add first-logged-in to users table

lib/travis/model/user.rb
Needed in order to update the attribute from api.
=> Make `first_logged_in_at` an accessible attribute

lib/travis/services/reset_model.rb
to help fix https://app.getsentry.com/travis-ci/travis-api/issues/99123870/ and https://app.getsentry.com/travis-ci/travis-api/issues/99131895/
=> check for current_user during run and accept?

lib/travis.rb, lib/travis/api/v0/pusher/build.rb, lib/travis/config/database.rb, lib/travis/config/defaults.rb, lib/travis/config/url.rb, lib/travis/github.rb, lib/travis/github/services/fetch_config.rb, lib/travis/github/services/sync_user/reset_token.rb, lib/travis/logs/services/archive.rb, lib/travis/mailer.rb, lib/travis/model/request.rb, lib/travis/model/user/oauth.rb, lib/travis/notification.rb, lib/travis/services/find_caches.rb, lib/travis/testing/stubs.rb, spec/support/active_record.rb, spec/travis/api/v0/event/build_spec.rb, spec/travis/api/v0/pusher/build_spec.rb, spec/travis/api/v0/pusher/job_spec.rb, spec/travis/api/v1/http/build_spec.rb, spec/travis/config_spec.rb, travis-core.gemspec
Josh has tested it on travis-enterprise
=> Changes for the travis-enterprise release

lib/travis/model/repository/settings.rb
@carlad Would you be so kind to merge it? Thanks :bouquet:
=> Remove pry

README.md
Also clarified the wording because it's a little confusing :)
=> Fix markdown error in readme

lib/travis/model/request/states.rb, spec/travis/model/request/states_spec.rb
Reverts travis-ci/travis-core#535
=> Revert " Downcase retrieved language on config before creating the build"

lib/travis/model/build/config.rb
this is the last one in line waiting to complete this issue:
https://github.com/hpi-swa/smalltalkCI/issues/106
already done: 
https://github.com/travis-ci/travis-build/pull/689
https://github.com/hpi-swa/smalltalkCI/pull/113
=> Smalltalk expansion

lib/travis/model/build.rb, spec/travis/model/build_spec.rb
This has been tested on staging (.org & .com)  and the previous issue found related to:
`install: pod setup`  on the .travis.yml, has been fixed
https://github.com/travis-pro/team-teal/issues/780
=> Remove case sensitive in language attribute

lib/travis/model/build.rb
Language should be modified before calling the expand_matrix method
=> Set language before expanding matrix

Gemfile
3.1.0 requires Ruby 2.2. https://rubygems.org/gems/listen/versions/3.1.0
=> Pin listen to < 3.1.0

lib/travis/requests/services/receive.rb
GitHub recently started returning wrong links for organisations -
instead of /orgs/org-name it sometimes returns /users/org-name. This
commit patches our code for the time being.
=> Fix payload in requests/receive service
