travis-ci/travis-core

db/migrate/20150121135400_jobs_add_received_at.rb, db/migrate/20150121135401_builds_add_received_at.rb, db/structure.sql, lib/travis/addons/pusher/event_handler.rb, lib/travis/api/v0/pusher/build.rb, lib/travis/api/v0/pusher/build/received.rb, lib/travis/api/v0/pusher/build/received/job.rb, lib/travis/api/v0/pusher/job.rb, lib/travis/api/v0/pusher/job/received.rb, lib/travis/enqueue/services/enqueue_jobs.rb, lib/travis/model/build/states.rb, lib/travis/model/job/test.rb, lib/travis/services/update_job.rb, spec/support/payloads.rb, spec/travis/model/build/states_spec.rb, spec/travis/model/job/test_spec.rb, spec/travis/services/update_job_spec.rb
Tested on Enterprise, needs to be bumped in hub. Should be good to be merged once web doesn't raise errors on `build:received` and `job:received` messages.
Note: this adds migrations
=> Add build/job :received state

lib/travis/services/find_build.rb, lib/travis/services/find_job.rb, spec/travis/services/find_build_spec.rb, spec/travis/services/find_job_spec.rb
to cut down on database and network load.
=> Exclude config blobs on demand for Job and Build

lib/travis/model/build/config.rb
This is required for https://github.com/travis-ci/travis-build/pull/394 to be able to create a build matrix for the "mono" key.
=> Add "mono" to EXPANSION_KEYS_LANGUAGE

lib/travis/model/commit.rb, spec/travis/model/commit_spec.rb
The compare URL for pull requests is just the pull request URL, so we can't extract the commit range from it, but the commit range is stored in the request for pull requests, so we can get it from there.
Fixes travis-ci/travis-ci#1719.
=> Return the right commit range for pull requests

lib/travis/model/job/queue.rb, spec/travis/model/job/queue_spec.rb
The intention here is to use `dist: trusty` (or similar) for queue
selection, so that we can safely deploy a test queue, and enable
feature flips for controlled testing.
=> Introduce `dist` as a possible key to be used for queue selection

lib/travis/model/job/queue.rb, spec/travis/model/job/queue_spec.rb
This has a few minor cleanup things from my previous PR:
- Remove the `education` queue matcher, it's no longer needed.
- Test that if there are no valid matchers, things behave correctly (nothing matches an empty configuration). This is the previous behaviour, I just added a spec to ensure it doesn't change
- Only check the matchers that we know about, and print warnings if queue configs use unknown matchers.
Also, this adds an `osx_image` matcher for routing jobs based on the `osx_image` config setting (which is feature flagged).
=> Add more job queue matchers

lib/travis/model/repository.rb
Unfortunately, we ended up with a few thousand repositories
without SSL key, because we changed the way Repository models
are instantiated.
(Basically, we bypassed the ActiveRecord hooks to generate them.)
There is no simple way to force key regeneration at the moment,
so we brute force the key generation by going into the console,
select the suspect Repositories and call `#regenerate_key!`
on them.
=> Coerce `Resporitoy#regenerate_key!` to really regenerate the key

.gitignore, db/migrate/20150414001337_add_lower_case_indices.rb, db/structure.sql
Adds lower case indices for for organizations.login, users.login, repositories.name and repositories.owner_name.
This way we can easily implement case insensitive APIs and UIs.
See travis-ci/travis-ci#3198, travis-ci/travis-ci#1545, travis-ci/travis-ci#2334, travis-pro/travis-admin#48, travis-pro/team-teal#81.
=> add lower case indices

lib/travis/api/v0/worker/job/test.rb, lib/travis/testing/stubs.rb, spec/travis/api/v0/worker/job/test_spec.rb
Currently we don't send default_branch to the worker, so it doesn't have
a knowledge on what branch to use by default, for example for caching.
=> Send repository.default_branch to the worker

lib/travis/requests/services/receive.rb
this way ActiveRecord is smart about knowing if a transaction is already created or not
removes warnings, and potentially bad side effects where a transaction is committed early
=> change to using connection.transaction

lib/travis/model/build.rb, spec/travis/services/find_builds_spec.rb
So that travis-web can request `/builds?event_type=push,api` for the time being.
/cc @drogus, @rkh
=> Accept multiple event types to Build.by_event_type

lib/travis/model/job/queue.rb, spec/travis/model/job/queue_spec.rb
In some cases we want to send a subset of jobs to a new queue, usually for testing out a new infrastructure of some sort. This allows specifying a percentag (in the range [0, 100)), and then the jobs will be distributed with weighted randomness. For example, consider this configuration:
``` YAML
- queue: builds.new-a
language: a
percentage: 25
- queue: builds.old-a
language: a
```
If you have 100 jobs with `language: a`, roughly 25 of them will go to builds.new-a, and the rest will go to builds.old-a.
The way the matching works is by stepping through each config from top to bottom, and applying the first one that matches. With this addition, the `percentage` key will cause it to be possible for the matching to continue to the next config even if the job matched the rest of the config.
/cc …
=> job-queue: allow random routing by percentage

Gemfile, db/structure.sql, lib/travis/model/repository.rb
This adds a sort order to `Repository.by_slug` so we don't rely on PostgreSQL's semi-random sort order when we have duplicate repository records.
=> Order repository by_slug

lib/travis/addons.rb, lib/travis/addons/README.markdown, lib/travis/addons/pushover.rb, lib/travis/addons/pushover/event_handler.rb, lib/travis/addons/pushover/instruments.rb, lib/travis/event/config.rb, spec/travis/addons/pushover/event_handler_spec.rb, spec/travis/addons/pushover/instruments/event_handler_spec.rb
This adds support for notifications via Pushover ( https://pushover.net/ )
This CR is a companion to https://github.com/travis-ci/travis-tasks/pull/28 ; see that for most of my description and commentary.
=> add pushover notification support

lib/travis/event/subscription.rb, spec/travis/event/subscription_spec.rb
After rescueing the exception also need to make sure the caller can deal with the return value.
With a certain event handler present in the config, but missing in the
code, our previous code would catch and log the fact that the constant
is missing. However, the method now also would return `true` (the return
value of `logger.error`), causing the caller to try to find a constant
on the value `true`, which of course would raise a new exception. This
is confusing, and not the behaviour one would expect: broken event
listener configuration should not break the application in general.
This change fixes that, changes the return value for `nil` in the
offending case, and deals with this value appropriately.
=> Improve error handling for event subscriptions looking at missing addons

lib/travis/requests/services/receive/api.rb, spec/travis/requests/services/receive/api_spec.rb
Should implement https://github.com/travis-pro/team-teal/issues/412. 
Needs to be deployed in gatekeeper.
=> Set compare_url when a request is created via api

lib/travis/travis_yml_stats.rb, spec/travis/travis_yml_stats_spec.rb
Keep track of deployment provider usage in `.travis.yml`.
```yaml
deploy:
provider: X
⋮
```
creates `deployment.provider: ["X"]` in Keen.io.
```yaml
deploy:
provider: X
⋮
provider: Y
⋮
```
creates `deployment.provider: ["X", "Y"]`, and
```yaml
deploy:
- provider: X
⋮
- provider: X
⋮
```
creates `deployment.provider: ["X", "X"]`.
=> Record deployment stats

lib/travis/travis_yml_stats.rb, spec/travis/travis_yml_stats_spec.rb
Create a new Keen event collection, "deployments" to track deployment data. Compare to "requests", there are far fewer of these (right now, anyway).
This allows easier query on Keen; e.g.,
```javascript
Keen.ready(function(){
var query = new Keen.Query("count_unique", {
eventCollection: "deployments",
groupBy: "provider",
targetProperty: "repository_id",
timeframe: "this_7_days",
timezone: "UTC"
});
client.draw(query, document.getElementById("my_chart"), {
// Custom configuration here
});
});
```
=> Tweak Keen dp

db/migrate/20150923131400_broadcasts_add_category.rb
This adds a "category" column to the broadcasts table which will enable us to define the category of broadcast (eg, "announcement" or "warning").
To define the broadcast admin (where broadcasts are created) will be updated.
=> add category column to broadcasts table

lib/travis/travis_yml_stats.rb
1. When user passes ill-formed data to `notifications` or `deploy`, we could see an exception when sending data to Keen. Instead of giving up entirely, we just ignore the data, so that we can still send requests data.
1. Normalize the notifiers and deployment provider names, so that, for example, `S3` and `s3` are considered the same.
1. Prevent `ArgumentError` when method signature does not match the payload. We had some issues when we introduced it.
=> Clean up Keen data collection issues

lib/travis/travis_yml_stats.rb
These payloads are either `nil` or an Array, so `#to_a`
normalizes them
=> Call `#size` only when appropriate

db/migrate/20151112153500_create_starred_repositories.rb
Adds a new `starred_repositories` table to the DB. This will be used to store information about which repos users have 'starred' to appear at the top of their dashboard.
This migration has been run on our `travis-staging` database without issues.
=> add migration for creating starred_repositories table

db/migrate/201511113111400_starred_repositories_add_index_user_id_and_repo_id.rb
To create a unique index on the starred_repositories table for user_is and repo_id.
This will ensure any concurrency possible errors are mitigated.
This migration has been run on the staging db successfully.
=> Cd starred repo index

lib/travis/model/build/config/dist.rb, spec/travis/model/build/matrix_spec.rb
Do not throw `NoMethodError` when matrix.include is empty
=> Handle empty matrix.include

lib/travis/model/log.rb
`parts.delete_all` will first fetch every log part and then do a delete query for each log part that is retrieved, while `Log::Part.where().delete_all` will run a single query to delete every log part. `delete_all` does mean that the callbacks are bypassed, but that was the same as the previous behaviour.
=> Optimize query that is done for clearing log parts

lib/travis/model/request/approval.rb, spec/travis/model/request/approval_spec.rb, spec/travis/model/request/states_spec.rb
The type for compare URLs in our database is VARCHAR(255).
Rather than accepting the request and throwing an exception
later (without a chance to let users know), we reject the
build request and advise to shorten branch/tag name.
=> Reject build request if compare URL is too long

lib/travis/model/branch.rb, lib/travis/model/build.rb, lib/travis/model/build/update_branch.rb, spec/travis/model/build/update_branch_spec.rb
At the moment a build's branch's `last_build_id` is not always consistent. I'm stumped at figuring out why that would happen, but it does.
This pull request should reduce some unnecessary complexity from this part of the logic, and adds an additional validation/logging step (can be removed once we've figured this out).
This stuff happens in Gatekeeper. We create a new build, and we regard this build as the "last build" on the build's branch.
Changes:
* Don't call updating the branch's `last_build_id` in the build's `after_save` hook. Use the `after_create` hook instead, because that's the timing we care about.
* Directly set the currently created `build.id` to `branch.last_build_id` instead of going through `repo.last_build_on(branch_name)`. This also spares a potentially expensive query. …
=> Reduce complexity of updating branch.last_build_id

lib/travis/model/build.rb, spec/travis/model/build/update_branch_spec.rb
https://github.com/travis-ci/travis-core/commit/672f4e595d59d8de9fcb746d8dfd4cfd7749c99a introduced a bug that now sets the current build to the branch's `last_build_id` even if it's a pull request build.
This change fixes that.
=> Only update the branch for push and api requests

lib/travis/model/build/config.rb
Add a R language key for matrix build support after https://github.com/travis-ci/travis-build/pull/621 is merged.
=> Add R language key

lib/travis/config/defaults.rb, spec/travis/config_spec.rb
This reinstates a timeout that was removed when db config got removed from the keychain.
Normally this would be set by `travis-config` but since there is a conflict between the version of Hashr `travis-config` needs, and the (earlier) version of Hashr `travis-core` requires, for now we need to set this variable here in `travis-core`.
When `travis-core` is eventually removed from `travis-api` we will be able to have api use `travis-config` to set this config variable.
I've checked this on api-staging to make sure the config variable is being loaded:
`{:adapter=>"postgresql",
:database=>"xxxx",
:encoding=>"unicode",
:min_messages=>"warning",
:variables=>{:statement_timeout=>10000, :application_name=>"api-staging-run.8545"},
:username=>"xxxx",
:password=>"xxxx", …
=> add statement_timeout to database config

.travis.yml
Since any app using `core` no longer uses Jruby, the requirement to run tests against Jruby has been removed from the travis.yml file.
I've checked that the following apps do not use jRuby:
admin-staging/production
gatekeeper-staging/prod
api-staging/production
Tests are passing locally and more than 25 mins quicker on travis-ci.
This addresses issue: travis-pro/team-teal#759
=> remove Jruby from .travis.yml

lib/travis/model.rb, lib/travis/model/log.rb, lib/travis/model/log/part.rb, lib/travis/model/logs_model.rb
Database connections in ActiveRecord are bound to a class, so in order
to use only one connection for both classes we need to have a shared
parent class.
=> Create shared parent class for logs classes

lib/travis/model/repository/settings.rb, spec/travis/model/repository/settings_spec.rb
Still needs a spec
This updates the repository to add a `rate_limit` attribute in the repository settings.
There is also validation to prevent the rate limit from being higher than 200.
=> Add attribute and validation for rate_limit

lib/travis/config/defaults.rb, lib/travis/model/repository/settings.rb, spec/travis/model/repository/settings_spec.rb
This updates the name of the rate limit for api builds, and configures default and maximum values through config.
The current default rate limit in effect is 10 requests per 30 seconds, so we have added a default value of 10.
The maximum limit suggested by @rkh was 200.
=> Update naming of api_builds_rate_limit

lib/travis/model/repository/settings.rb, spec/travis/model/repository/settings_spec.rb
Returning nil if nothing is set, in order to use config values on the API
=> Return nil if no value is set for api_builds_rate_limit

lib/travis/services/find_caches.rb
Hashr does not appear to implement `#slice`, and we are getting
`{}` when we call it.
=> Coerce config into a Hash before passing it to S3 service

lib/travis/model/request/states.rb, spec/travis/model/request/states_spec.rb
The language attribute  in `.travis.yml` should be downcased before creating the build
https://github.com/travis-pro/team-teal/issues/780
=>  Downcase retrieved language on config before creating the build

lib/travis/model/build.rb, lib/travis/model/build/config/language.rb, spec/travis/model/build_spec.rb
This modifies the way we set  `config[:language]` on the Language class, in order to downcase it or use the DEFAULT_LANGUAGE. 
This way, the language modification is propagated to the database, accessible everywhere, and mainly the `language` attribute on the .travis.yml file won't be case sensitive anymore.
=> Downcase language directly on the Language class

lib/travis/services/delete_caches.rb, lib/travis/services/find_caches.rb, spec/support.rb, spec/support/gcs.rb, spec/travis/services/find_caches_spec.rb, travis-core.gemspec
This PR adds the ability to access caches backed by Google Cloud Storage using [google-api-client](https://rubygems.org/gems/google-api-client).
The configuration would look like:
```yaml
cache_options:
- s3:
access_key_id: AK*************Q
secret_access_key: U*******************O
bucket_name: foo-bar-coffee-buzz-buzz
- gcs:
project_id: foo-bar-1234567
json_key: | # we need a string here to create a StringIO object
{
"type": "service_account",
"project_id": "foo-bar-1234567",
"private_key_id": "1234567890abcdef",
"private_key": "-----BEGIN PRIVATE KEY-----\nPRIVATE_KEEEEEY\n-----END PRIVATE KEY-----\n",
"client_email": "foo@example.com",
"client_id": "387143871333",
"auth_uri": "https://accounts.google.com/o/oauth2/auth",
"token_uri": "https://accounts.google.com/o/oauth2/token", …
```
=> Add GCS cache listing ability

lib/travis/model/build/config/matrix.rb, spec/travis/model/build/matrix_spec.rb
And ignore `allow_failures` silently.
Another reasonable behavior would be to try to match the scalar value with a job in the matrix and exclude that. This approach will require some extra work while processing config to ensure that the data structures match.
=> Ensure allow_failures config is an array

lib/travis/model/job.rb, spec/travis/model/job_spec.rb
We should drop non-Hash addons config when a top-level
deploy key is present.
When the top-level deploy key is present, while normalizing,
an addons value that is not a Hash will be sent `#[]`,
which is raises `NoMethodError`.
=> Ensure config[:addons] is reasonable when deploy is present

lib/travis/requests/services/receive/pull_request.rb
Under certain circumstances the payload from GitHub could lack
data we assume to exist, leading to NoMethodError
=> Ensure `#commit` does not throw NoMethodError

lib/travis/model/request/approval.rb, spec/travis/model/request/approval_spec.rb
Fixes https://github.com/travis-ci/travis-ci/issues/5933
If `.travis.yml` contains a YAML syntax error on the `gh-pages`
branch, we display the error message "github pages branch" even if
`gh-pages` is (textually) whitelisted in that file.
We should display "missing config" instead.
=> Prefer 'missing config' error message to 'github pages branch'

lib/travis/model/request/approval.rb, lib/travis/model/request/states.rb, spec/travis/model/request/approval_spec.rb
Config can be blank if exception is thrown while processing the file
due to YAML syntax error
=> Tweak 'config missig' error message

lib/travis/model/build.rb
After some DB digging it was apparent that postgres was handling the following API request without using any indexes, resulting in incredibly long request times and causing time outs.
https://api.travis-ci.org/repos/twbs/bootstrap/builds?after_number=1500
Adding a three-column index plus adjusting the query to order by `build.number` meant postgres would then utilise this index and run the query in a fraction of the time.
Tests are passing on Travis-ci and a branch of api has been updated and pushed to staging, where all is working correctly.
This addresses this issue: https://secure.helpscout.net/conversation/194688663/28221/?folderId=30784
=> Improve query for listing builds `after-number` (i.e. builds `older_than`)

.travis.yml, Gemfile, spec/travis/states_cache_spec.rb
This PR adds memcached service to the builds, so that we do not skip tests related to it.
This also alters an existing spec, which does not appear to have been tested until now.
=> Enable memcached in tests

lib/travis/model/request/approval.rb, spec/travis/model/request/approval_spec.rb
I moved the config.blank? condition to the end of the method. It was preventing the other cases to fall first (e.g. github_pages), and therefore it is hard to debug some request issues. 
Found this with @MariadeAnton
=> Show correct error messages in Request::Approval

lib/travis/services/find_admin.rb, lib/travis/testing/stubs.rb, spec/travis/services/find_admin_spec.rb
This PR fixes the problem of missing PR builds, for repos where the admin is not found.
Travis will check for the first 15 users with github tokens and admin rights on the repo. The user permissions' data could be outdated since user permissions are synced with github, only once a day. 
So, the candidate is checked for admin rights again.
The number of candidates is set to be large to reduce the probability of missing a build when the first few candidates aren't valid admins.
An invalid admin's admin permission is revoked, on our side too.
If no admin is found, which could be the case, when a user's admin rights have been revoked recently or their account has been deleted, `Travis::AdminMissing` error is raised. This error is picked up to re-try the build later.
=> Fix PRs being skipped when Github returns a 401/404 for a missing admin

.travis.yml
Been getting some build failures around [JRuby and some utf-8 characters](https://travis-ci.org/travis-ci/travis-core/builds/143346961). [No apps in Enterprise (or at all?) that use `travis-core` also use jruby](https://travisci.slack.com/archives/enterprise/p1468240037003637) so this change is safe and in line with what we're doing in master.
=> Update .travis.yml to match ruby versions in master

lib/travis/services/find_caches.rb
Schibsted reported an issue where build caching was working but the UI would 500. Tracked this down to a case where the code expected a `Hashr` hash to be recursive when using `.to_h` and the resulting nested `Hashr` hash swallowed the `slice` returning `nil` (since `Hashr` uses `method_missing` to allow you to use methods as hash keys). 
This has come up before with SSL settings. Something to look out for. Also may make sense to do some checking around method names or if args are being passed. Removing the `method_missing` may be too much since that's one of the large things that `Hashr` does. 
It may also be the case that this is or isn't still a problem in master (this is fixing a 2.0 bug).
=> Fix cache UI in Enterprise. 

lib/travis/config/url.rb, spec/travis/config_spec.rb
`travis-core` is on a really old version of `travis-config`. Which is unfortunate since we have some customers that want to use the `amqps://` protocol with their RabbitMQ setup. 
Since `travis-core` is currently deprecated and the jump to the newest version of `travis-config` requires a lot of changes it doesn't make sense to simply do an upgrade the newest version. So instead what we'll do is patch in support in `master` then back port this change to the enterprise branches.
=> Port ampqs protocol support from travis-config

lib/travis/config/url.rb, spec/travis/config_spec.rb
Backport of #559 to the `te-dev` branch.
=> Enterprise Backport #559: Port ampqs protocol support from travis-config

lib/travis/services/sync_user.rb, spec/travis/services/sync_user_spec.rb
Sync 2.0 now uses the queue `sync` (was: `user_sync`). It currently still polls on the old queue names and has a backwards compatibility class so API still works.
Admin should push to the new queue `sync`, and use the class name `Travis::GithubSync::Worker`.
Like so:
```ruby
Sidekiq::Client.push(
'queue' => 'sync',
'class' => 'Travis::GithubSync::Worker',
'args'  => [user_id: id]
)
```
=> Talk to the Sync 2.0 queue
